name: Run Tests and Generate Reports

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

stages:
  - test

pytest:
  stage: test
  image: python:3.9
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - pip3 install --upgrade pip
    - pip3 install pytest
    - if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - pytest -v --junitxml=report.xml
    - pytest -v --html=../results/report.html
  artifacts:
    when: always
    reports:
      junit: report.xml
