name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add Conda to system path
      run: |
        echo "$CONDA/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file python-package-conda.yml --name base
        conda install flake8 pytest
    - name: Lint with flake8
      run: |
        # Linting with flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
